name: Run daily build recipes automatically or manually

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run on 0:00 UTC 

jobs:
  run:
    runs-on: [self-hosted, Linux, simulation, zeus]
    steps:
      - uses: actions/checkout@v6

      - name: Install Python 3.12 on Fedora (if missing)
        run: |
          if ! command -v python3.12 &> /dev/null; then
            sudo dnf install -y python3.12 python3.12-pip
          fi
          python3.12 --version

      - name: Use Python 3.12
        run: |
          python3.12 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          ln -sf /usr/bin/python3.12 $HOME/python
          echo "export PATH=$HOME:$PATH" >> $GITHUB_ENV
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install -e .
          python3.12 -m pip install git+https://github.com/AstarVienna/ScopeSim_Templates.git
          python3.12 -m pip install git+https://github.com/AstarVienna/ScopeSim_Data.git
          python3.12 -m pip install git+https://github.com/AstarVienna/ScopeSim.git
          python3.12 -m pip install astar-utils numpy more-itertools astropy PyYAML

          SCOPE_SIM_SITE=$(python3.12 -c "import sysconfig; print(sysconfig.get_paths()['purelib'])")
          echo "PYTHONPATH=$SCOPE_SIM_SITE:$GITHUB_WORKSPACE:${PYTHONPATH:-}" >> $GITHUB_ENV
          python3.12 -c "import scopesim; print(scopesim.__file__)"
          python3.12 -c "import metis_simulations; print(metis_simulations.__file__)"

          git clone https://github.com/AstarVienna/irdb.git # get bleeding edge version of irdb

      - name: Run recipes
        run: |
          cd "$GITHUB_WORKSPACE"
          export DEFAULT_IRDB_LOCATION="inst_pkgs"
          ln -sfn "$GITHUB_WORKSPACE/irdb" "$GITHUB_WORKSPACE/inst_pkgs" # link to git-cloned version of irdb
          
          export MSIM_YAML_DIR="YAML/ESO"
          export MSIM_NCORES=4
          export DEFAULT_IRDB_LOCATION="inst_pkgs"
          export MSIM_OUTDIR="output"

          python simulationBlocks/imgLM.py
          ./runESO.sh
      
      - name: Move data to /data
        run: |
          cd "$GITHUB_WORKSPACE/"
          TODAY=$(date +%Y-%m-%d)
          echo "Today's date: $TODAY"
          mkdir -p /data/$TODAY
          cp -a output/. /data/$TODAY/
          cd /data
          ln -sfn $TODAY LatestBuild
          ls -la /data/$TODAY